---

- name: Create s3 bucket 
  aws_s3:
    bucket: "{{ bucket_name }}"
    mode: create
    permission: private 
#
- name: Create policy file for bucket
  template:
    src: "{{ role_path }}/templates/s3-web-access-policy.json.j2"
    dest: "{{ role_path}}/files/s3-web-access-policy.json"
 
- name: Apply policy
  command: "aws s3api put-bucket-policy --bucket {{ bucket_name }} --policy file:///{{ role_path }}/files/s3-web-access-policy.json"

#- name: Create other buckets
#  aws_s3:
#    bucket: "{{ item }}"
#    mode: create
#    permission: public-read
#  with_items:
#    - "{{ other_buckets }}"
