---
# tasks file for webapp

    - name: update apt repo and cache
      become: yes
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: upgrade pacakges
      become: yes
      apt: upgrade=dist force_apt_get=yes

    - name: Check if a reboot is needed on all servers
      register: reboot_required_file
      stat: path=/var/run/reboot-required get_md5=no
    
    - name: Reboot the server if kernel updated
      become: yes
      reboot:
        msg: "Reboot initiated by Ansible for kernal updates"
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists

    - name: install Apache httpd server
      become: yes
      apt:
        name: apache2
        update_cache: yes
        state: latest

    - name: overwrite default Apache config
      become: yes
      template:
        src: templates/apache2.conf.j2
        dest: /etc/apache2/apache2.conf

    - name: Replace the default configuration
      become: yes
      template:
        src: templates/000-default.conf.j2
        dest: /etc/apache2/sites-available/000-default.conf

    - name: Add php info file for testing
      become: yes
      template:
        src: templates/info.php.j2
        dest: /var/www/html/info.php

    - name: Enable mod_rewrite, mod_expires, mode_deflate, ssl
      become: yes
      shell: "a2enmod rewrite expires deflate ssl"

    - name: Install PHP and modules
      become: yes
      apt:
        name: "{{ item  }}"
        state: present
      loop:
        - php
        - php-common
        # - php-cli # Don't need these modules.
        # - php-mysql
        # - php-pdo
        # - php-curl
        # - php-bz2
        # - php-curl
        # - php-gd
        # - php-imap
        # - php-mbstring
        # - php-zip
        # - php-xml

    - name: Restart Apache service
      become: yes
      shell: "service apache2 restart"