---
# vars file for webapp

ec2_key_name: "sysadmin-ec2-key"
ec2_private_key_dir: "/home/mason/.ssh/sysadmin-ec2-key.pem"
region: ap-southeast-2
instance_type: t2.micro
security_group: "sg_webservers"
subnet_id:
    #ap-southeast-2a
    - subnet-f72b8d91 
    #ap-southeast-2b
    - subnet-35c0137d 
    #ap-southeast-2c
    - subnet-4f194917
image: ami-0567f647e75c7bc05